s3:
    access_key_id: 'AKIAJYGYJNJKYGNDGGCQ'
    secret_access_key: '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'
    bucket_name: 'recome-new'

image_settings:
    horizontal_res: 640
    vertical_res: 480
    file_name: 'test'
    file_extension: '.jpg'
    folder_name: 'images'
    awb_mode: 'auto'
    photo_interval: 60

debug: true